# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: MAGIC MAVEN

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Maven Dependency Analyze Dep Mgt
      run: mvn -fn dependency:analyze-dep-mgt

#    - name: Maven Dependency Tree
#      run: mvn -fn dependency:tree
      
#    - name: Maven Dependency Resolve
#      run: mvn -fn dependency:resolve

#    - name: Maven Dependency Sources
#      run: mvn -fn dependency:sources

#    - name: Maven Dependency Copy
#      run: mvn -fn dependency:copy

#    - name: Maven Dependency Analyze
#      run: mvn -fn dependency:analyze

#    - name: Maven Dependency List
#      run: mvn -fn dependency:list

    - name: Maven Dependency go-offline
      run: mvn -fn dependency:go-offline

#    - name: Maven Dependency Unpack
#      run: mvn -fn dependency:unpack

#    - name: Maven Dependency Get
#      run: mvn -fn dependency:get


#      run: mvn -fn dependency:copy, analyze, unpack, list, sources, go-offline, get, tree

#      run: mvn -fn dependency: among available goals copy, analyze, unpack, list-repositories, resolve, resolve-plugins, build-classpath, list, analyze-dep-mgt, sources, analyze-duplicate, copy-dependencies, unpack-dependencies, go-offline, get, purge-local-repository, properties, analyze-report, tree, analyze-only, help

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
#    - name: Update dependency graph
#      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
